### ISSUE TITLE
ERROR:root:error processing request of type end: signed integer is greater than maximum

### ISSUE THREAD

**Issue by ashishkaransingh** [atroncy/kapacitor_prophet-udf#2]
Thanks a lot of the creation of the script and advise on the last issue!
I have made an immense progress, kapacitor can now access udf_prophet.sock and i can access @prophet in kapacitor tickscript.

But now i am getting an error after i enable the task.
Please advise.

Call stack-

```
INFO:root:Agent finished connection 2
INFO:root:Starting Agent for connection 3
INFO:root:init 
INFO:root:begin batch
INFO:root:fit model

Traceback (most recent call last):
  File "/home/linuxuser/.local/lib/python2.7/site-packages/kapacitor/udf/agent.py", line 124, in _read_loop
    self.handler.end_batch(request.end)
  File "/etc/kapacitor/prophet.py", line 145, in end_batch
    m.fit(df)
  File "/home/linuxuser/.local/lib/python2.7/site-packages/fbprophet/forecaster.py", line 1057, in fit
    history = self.setup_dataframe(history, initialize_scales=True)
  File "/home/linuxuser/.local/lib/python2.7/site-packages/fbprophet/forecaster.py", line 241, in setup_dataframe
    df['ds'] = pd.to_datetime(df['ds'])
  File "/home/linuxuser/.local/lib/python2.7/site-packages/pandas/core/tools/datetimes.py", line 592, in to_datetime
    values = convert_listlike(arg._values, True, format)
  File "/home/linuxuser/.local/lib/python2.7/site-packages/pandas/core/tools/datetimes.py", line 302, in _convert_listlike_datetimes
    allow_object=True)
  File "/home/linuxuser/.local/lib/python2.7/site-packages/pandas/core/arrays/datetimes.py", line 1857, in objects_to_datetime64ns
    require_iso8601=require_iso8601
  File "pandas/_libs/tslib.pyx", line 460, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 685, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 809, in pandas._libs.tslib.array_to_datetime_object
  File "pandas/_libs/tslib.pyx", line 803, in pandas._libs.tslib.array_to_datetime_object
  File "pandas/_libs/tslibs/parsing.pyx", line 99, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "/home/linuxuser/.local/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/linuxuser/.local/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 655, in parse
    ret = self._build_naive(res, default)
  File "/home/linuxuser/.local/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 1238, in _build_naive
    if cday > monthrange(cyear, cmonth)[1]:
  File "/usr/lib/python2.7/calendar.py", line 121, in monthrange
    day1 = weekday(year, month, 1)
  File "/usr/lib/python2.7/calendar.py", line 113, in weekday
    return datetime.date(year, month, day).weekday()
OverflowError: signed integer is greater than maximum
ERROR:root:error processing request of type end: signed integer is greater than maximum
```

Thanks

**Comment by ashishkaransingh** [comment]
Tickscript i am using


```
var data = batch
    |query('''
    SELECT mean("Percent_Processor_Time") as value FROM "influxserver_test"."autogen"."Processor" WHERE "instance"='_Total'
    ''')
        .period(30d)
        .every(1m)
        .groupBy(time(1h))
        .offset(5m)
        .align()
    |log()

data
    @prophet()
        .periods(24)
        .field('value')
        .freq('H')
        .changepoint_prior_scale(0.001)
        .include_history(FALSE)
    |log()
    |influxDBOut()
        .database('influxserver_test')
        .measurement('fbprophet')

```

**Comment by ashishkaransingh** [comment]
FYI from the same server i was able to use prophet and the same dataset using jupyter notebook.
A similar error for a different software was reported here:
https://github.com/Yelp/elastalert/issues/1697#issuecomment-389677437

**Comment by ashishkaransingh** [comment]
I realized that in my jupyter notebook i had to handle the time in the following manner:
df.ds =  pd.to_datetime(df.ds).dt.tz_convert(None)
Without which notebook threw the following error:
ValueError: Column ds has timezone specified, which is not supported. Remove timezone.

How can we update this line of code so it handles the time format:

```
time
2019-12-10T17:25:07.000Z
2019-12-10T17:26:07.000Z
2019-12-10T17:27:05.000Z
```

**Comment by ashishkaransingh** [comment]
In prophet.py could not handle like this:

        d = {'y': y, 'ds': ds}
        df = pd.DataFrame(d)
        ## Handle timeformat
        df.ds = pd.to_datetime(df.ds).dt.tz_convert(None)

ERROR:root:error processing request of type end: Cannot convert tz-naive timestamps, use tz_localize to localize

Please advise!

**Comment by ashishkaransingh** [comment]
@atroncy Please advise?

**Comment by atroncy** [comment]
Hi @ashishkaransingh,

It seems as you said that the prophet lib has some issue with your timestamp.
I'm not well versed with pandas/python in general, so I sadly don't think I will be able to help you that much on this one.

Although, If you look at this doc, https://facebook.github.io/prophet/docs/quick_start.html#python-api, the prophet team recommend your timestamp to be in those formats eg: YYYY-MM-DD for a date or YYYY-MM-DD HH:MM:SS for a timestamp. Maybe if you use those formats this will end up working better for you.

In any case you should also check this repo https://github.com/nathanielc/tick-prophet/blob/master/prophet_udf.py . This tick script was made by the developer of kapacitor (the guy in the video!), they are probably some improvements compared to my script, as I'm not much of a python dev myself.

**Comment by ashishkaransingh** [comment]
Thank you so much @atroncy !

**Comment by ashishkaransingh** [comment]
I will further look into it.
